language: node_js

arch:
  - amd64
  - arm64

dist:
  - bionic

node_js:
  - "lts/*"
  - "10"
  - "14"

services:
  - mongodb

env:
  - NODE_ENV=travis

before_script:
  - sudo apt-get install -qq ghostscript

script:
  - npm test

after_script:
  - sleep 10
  - pm2 desc 0
  - pm2 logs www --nostream
  - pm2 stop all
  - sleep 20

notifications:
  email: false
