language: node_js

services:
  - mongodb

env:
  - NODE_ENV=travis

before_script:
  - sudo apt-get install -qq ghostscript
  - npm start
  - sleep 5
  
script:
  - npm test
  
after_script:
  - sleep 120
  - pm2 desc 0  
  - pm2 stop all
  - sleep 5
  - cat /home/travis/.pm2/logs/www-out-0.log
  - cat /home/travis/.pm2/logs/www-error-0.log

node_js:
  - "lts/*"
  - "8"
  - "9"
  
notifications:
  email: false
