sudo: required

language: node_js

arch:
  - amd64

dist:
  - bionic

node_js:
  - "lts/*"

services:
  - docker

env:
  - NODE_ENV=travis

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose build
  - docker-compose pull --ignore-pull-failures
  - docker-compose up -d
  - sleep 3
  - docker ps
  - sleep 14
  - docker logs papierkorb-app
  - sleep 1
  - docker logs papierkorb-mongo
  - sleep 1
  - docker logs papierkorb-nginx
  - sleep 1

script:
  - npm test
  - cd pkjs-api && npm test

after_script:
  - sleep 10
  - docker logs papierkorb-app
  - sleep 1
  - docker logs papierkorb-mongo
  - sleep 1
  - docker logs papierkorb-nginx
  - docker-compose down

notifications:
  email: false
