language: node_js

services:
  - mongodb

env:
  - NODE_ENV=travis TESSDATA_PREFIX=/usr/local/share/tesseract-ocr/tessdata/

before_script:
  - sudo apt-get install -qq ghostscript pdftk poppler-utils curl
  #- git clone https://github.com/DanBloomberg/leptonica.git leptonica
  #- cd leptonica && ./autobuild && ./configure && make && sudo make install && sudo ldconfig
  #- cd ..
  #- git clone https://github.com/tesseract-ocr/tesseract.git tesseract-ocr
  #- cd tesseract-ocr && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig
  #- cd ..
  - curl -s https://packagecloud.io/install/repositories/marcproe/tesseract-rpi/script.deb.sh | sudo bash
  - sudo apt-get update
  - sudo apt-get install leptonica=99-1
  - sudo apt-get install tesseract=99-1

  - tesseract -v

  - sudo wget -P /usr/local/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata
  - sudo wget -P /usr/local/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/deu.traineddata
  - sudo wget -P /usr/local/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/nld.traineddata
  - sleep 3
  - npm start
  - sleep 5
  
script:
  - npm test
  
node_js:
  - "lts/*"
  
notifications:
  email: false
