language: node_js


before_script:
  - sudo apt-get install -qq ghostscript
  - sudo apt-get install -qq pdftk
  - sudo apt-get install -qq tesseract-ocr
  - sudo apt-get install -qq poppler-utils
  - sudo wget -P /usr/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata
  - sudo wget -P /usr/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/deu.traineddata
  - sudo wget -P /usr/share/tesseract-ocr/tessdata/ https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/nld.traineddata
  
node_js:
  - "lts/*"

notifications:
  email: false
