version: "2"
services:
  papierkorb-app:
    container_name: papierkorb-app
    image: papierkorb-app
    build: .
    restart: always
    links:
      - papierkorb-mongo
    environment:
      - NODE_ENV=docker
    volumes:
      - ./mnt/papierkorb.js:/opt/papierkorb

  papierkorb-mongo:
    container_name: papierkorb-mongo
    restart: always
    image: sumglobal/rpi-mongodb
    volumes:
      - ./data:/data/db

  papierkorb-nginx:
    container_name: papierkorb-nginx
    image: papierkorb-nginx
    build: docker/nginx/
    restart: always
    ports:
      - "80:80"
    links:
      - papierkorb-app
